# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DGxe5LnfKtpUo-esAYEWGEFffso2cEp3
"""

# # Install Streamlit and a tunneling tool (localtunnel)
# !pip install -q streamlit
# !npm install -g localtunnel

# pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import yaml

# import sys
# sys.path.append('/content/gdrive/code/alpaca_broker')
# from google.colab import drive
# drive.mount('/content/gdrive')

from streamlit_autorefresh import st_autorefresh

st_autorefresh(interval=5000, key="refresh")

st.title("User Interface")
st.write("Hello world!")

import pandas as pd
from datetime import datetime

st.set_page_config(page_title="Trading Dashboard", layout="wide")

st.title("Algorithmic Trading Dashboard")

# Allow for API and secret keys file read
from dotenv import load_dotenv
import os

from execution.alpaca_broker import AlpacaPaperBroker
from data.historical import HistoricalDataService

load_dotenv()
API_KEY = os.getenv("ALPACA_API_KEY")
SECRET_KEY = os.getenv("ALPACA_SECRET_KEY")

broker = AlpacaPaperBroker(
    API_KEY,
    SECRET_KEY
)

print(API_KEY is not None)

account = broker.get_account()
positions = broker.get_positions()

import time

from data.market_data import get_latest_bars
from engine.trading_engine import PaperTradingEngine

engine = PaperTradingEngine()
bars = HistoricalDataService()

engine.start()

while engine.enabled:

    bar = bars.get_daily_bars()

    executions = engine.run_cycle(bar)

    if executions:
        print(executions)

    time.sleep(60)

st.header("System Status")

col1, col2, col3 = st.columns(3)

with col1:
    st.metric(
        "Equity",
        f"${float(account.equity):,.2f}"
    )

with col2:
    st.metric(
        "Cash",
        f"${float(account.cash):,.2f}"
    )

with col3:
    st.metric(
        "Buying Power",
        f"${float(account.buying_power):,.2f}"
    )

st.write("Last update:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

st.divider()

col1, col2, col3 = st.columns(3)

# with col1:
#     st.metric("Connection", "Connected")

# with col2:
#     st.metric("Mode", "Paper Trading")

# with col3:
#     st.metric("Strategy", "Running")

try:
    account = broker.get_account()
    connected = "Connected"
except Exception:
    connected = "Disconnected"

col1.metric("Connection", connected)
col2.metric("Mode", "Paper Trading")
col3.metric("Strategy", "Running")

# connected = "Connected" if account else "Disconnected"

st.header("Portfolio")

rows = []

for symbol, pos in positions.items():

    pnl = (
        pos.current_price -
        pos.average_entry_price
    ) * pos.quantity

    rows.append({
        "Ticker": symbol,
        "Qty": pos.quantity,
        "Avg Price": pos.average_entry_price,
        "Current Price": pos.current_price,
        "PnL": round(pnl, 2)
    })

df = pd.DataFrame(rows)

st.dataframe(df, use_container_width=True)

st.header("Recent Orders")

orders = broker.get_recent_orders()

rows_1 = []

for order in orders:
    rows_1.append({
        "Time": order.submitted_at,
        "Symbol": order.symbol,
        "Side": order.side,
        "Qty": order.qty,
        "Status": order.status
    })

st.dataframe(pd.DataFrame(rows_1))

st.header("Controls")

if st.button("Start Strategy"):
    st.success("Strategy Started")
    engine.start()

if st.button("Stop Strategy"):
    st.warning("Strategy Stopped")
    engine.stop()

# #whenever strat generates a signal, log and append it to csv
# signal = {
#     "Time": datetime.now(),
#     "Ticker": "AAPL",
#     "Signal": "BUY",
#     "Reason": "20 MA crossed 50 MA"
# }

for ticker in ["AAPL", "MSFT", "SPY", "QQQ", "NVDA"]:
  signal = strategy.generate_signal(ticker)

#so streamlit reads the above code

st.header("Recent Signals")
st.table(signals)
try:
    signals = pd.read_csv("logs/signals.csv")
    st.header("Recent Signals")
    st.dataframe(signals.tail(10))
except FileNotFoundError:
    st.info("No signals have been generated yet.")

st.dataframe(signals.tail(10))

mode = st.radio(
    "Trading Mode",
    ["Backtest","Paper Trading"]
)

st.write("Current mode:", mode)

st.header("Risk Settings")

max_position = st.number_input(
    "Max Position Size",
    value=100
)

max_daily_loss = st.number_input(
    "Max Daily Loss ($)",
    value=500
)

risk_percent = st.slider(
    "Risk Per Trade (%)",
    0.5,
    5.0,
    2.0
)

# import json

if st.button("Save Configuration"):

    config = {
        "max_position": max_position,
        "max_daily_loss": max_daily_loss,
        "risk_percent": risk_percent,
        "mode": mode
    }

    with open("settings.yaml", "r") as f:
        settings = yaml.safe_load(f)

    settings["risk"] = {"max_position": max_position,
    "max_daily_loss": max_daily_loss,
    "risk_percent": risk_percent,
}

    settings["mode"] = mode

    with open("settings.yaml", "w") as f:
        yaml.safe_dump(settings, f, sort_keys=False)

    st.success("Configuration Saved")

# npm install --save-dev localtunnel@2.0.2
# !streamlit run app.py & npx localtunnel --port 8501